'use strict';
const P=Planner;
const weekdayNames=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const weekdayShort=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
function monthName(date){return new Intl.DateTimeFormat('pt-BR',{month:'long'}).format(new Date(date+'T12:00:00'));}
function weekdaysText(days){return [1,2,3,4,5,6,0].filter(d=>days.includes(d)).map(d=>weekdayShort[d]).join(' · ');}
function goalOverview(){
 const p=P.settings(state);
 if(!p.configured)return `<section class="goal-overview"><div class="eyebrow">FECHAR O MÊS NO AZUL</div><h2>Quanto precisa entrar?</h2><p>Configure suas contas e os gastos da semana para descobrir suas metas diárias e semanais.</p>${btn('goal-settings','Definir minhas metas','primary full')}</section>`;
 const f=P.monthPlan(state);
 return `<section class="goal-overview"><div class="row"><div class="eyebrow">PARA FECHAR ${monthName(f.at).toUpperCase()}</div><span class="pill ${f.needed?'neutral':''}">${f.needed?'Meta em andamento':'Plano coberto'}</span></div><div class="goal-total">${C.money(f.needed)}</div><p class="small muted">${f.needed?'Ainda precisa entrar até '+shortDate(f.end)+', incluindo a sobra desejada.':'Os saldos cobrem os gastos previstos e a sobra desejada.'}</p><div class="goal-pair"><div><span>Média por dia de trabalho</span><strong>${f.averageDaily===null?'Sem dias restantes':C.money(f.averageDaily)}</strong></div><div><span>${f.next?'Até '+shortDate(f.next.date):'Fora do calendário'}</span><strong>${C.money(f.next?f.next.amount:f.offSchedule)}</strong></div></div>${f.offSchedule?`<p class="warning">${C.money(f.offSchedule)} precisam entrar fora do calendário de recebimentos. Confira os vencimentos em Metas.</p>`:''}${btn('show-goals','Ver metas e vencimentos','subtle full')}</section>`;
}
function renderGoals(){
 const p=P.settings(state);
 if(!p.configured){app.innerHTML=`<div class="eyebrow">RENDA COM DESTINO</div><h1>Suas metas</h1>${goalOverview()}<p class="note">O sistema considera o saldo disponível, as contas ainda não pagas e os gastos previstos até o fim do mês. Transferências entre seus bancos não contam como renda.</p>`;return;}
 const f=P.monthPlan(state),weekly=p.paymentMode==='weekly';
 const nextDate=f.next?.date;
 app.innerHTML=`<div class="eyebrow">${monthName(f.at).toUpperCase()} · ATÉ ${shortDate(f.end)}</div><div class="heading"><h1>Fechar o mês no azul</h1>${btn('goal-settings','Ajustar metas','subtle')}</div>
 <section class="goal-overview"><span class="small">AINDA PRECISA RECEBER</span><div class="goal-total" id="month-needed">${C.money(f.needed)}</div><p>${f.needed?'Essa é a entrada líquida que falta para cobrir o plano e terminar com a sobra escolhida.':'Os saldos atuais cobrem o plano informado.'}</p><div class="goal-pair"><div><span>Mínimo para cobrir os gastos</span><strong id="minimum-needed">${C.money(f.minimum)}</strong></div><div><span>Sobra desejada no fim do mês</span><strong>${C.money(p.buffer)}</strong></div></div></section>
 <div class="goal-grid"><section class="card"><div class="eyebrow">META DIÁRIA</div><h2 id="daily-goal">${f.averageDaily===null?'Sem dias restantes':C.money(f.averageDaily)}</h2><p class="small muted">Média equivalente por dia de trabalho: ${f.workRemaining} dias ainda podem gerar recebimento neste mês.</p><p class="small">${weekdaysText(p.workdays)}</p><p class="small muted">${weekly?'Você recebe no '+weekdayNames[p.payday].toLowerCase()+'. Essa média orienta o trabalho; não significa que o dinheiro entra todos os dias.':'O valor de cada dia pode aumentar para cobrir um vencimento próximo. Confira a agenda abaixo.'}</p></section>
 <section class="card"><div class="eyebrow">${weekly?'PRÓXIMO RECEBIMENTO':'META NESTA SEMANA'}</div><h2 id="weekly-goal">${C.money(weekly?(f.next?.amount||0):(f.weeks.find(w=>w.start===P.weekStart(f.at))?.amount||0))}</h2><p class="small muted">${weekly?(nextDate?'Para receber em '+fullDate(nextDate)+'.':'Nenhum recebimento programado até o fim do mês.'):'Soma das entradas que ainda faltam nesta semana.'}</p><p class="small">Já entrou nesta semana: <strong id="week-received">${C.money(f.incomeWeek)}</strong></p><p class="small muted">Já entrou neste mês: ${C.money(f.incomeMonth)}. As metas restantes já descontam essas entradas.</p></section></div>
 ${f.offSchedule?`<section class="warning" id="cash-warning"><h2>Dinheiro necessário antes do pagamento</h2><p><strong>${C.money(f.offSchedule)}</strong> precisam entrar fora do calendário ${nextDate?'antes de '+shortDate(nextDate):'até '+shortDate(f.end)} para cumprir o plano.</p>${f.firstRisk?`<p class="small">Primeira falta de saldo prevista: ${shortDate(f.firstRisk.date)}${f.firstRisk.bills.length?' · '+f.firstRisk.bills.map(esc).join(', '):' · gastos do dia a dia'}. Até essa data faltam ${C.money(f.firstRisk.amount)}.</p>`:''}<p class="small">Somente receber no dia programado não resolve esse intervalo. Antecipe uma entrada, ajuste os gastos ou revise os vencimentos.</p></section>`:''}
 <section class="section"><h2>Quanto precisa entrar por semana</h2><p class="small muted">Somente o que falta, a partir de hoje. Contas próximas podem concentrar a meta nas primeiras semanas.</p><div class="card" id="weekly-schedule">${f.weeks.length?f.weeks.map(w=>`<div class="line row"><div><strong>${shortDate(w.start<f.at?f.at:w.start)} a ${shortDate(w.end)}</strong><div class="small muted">${weekly?'Receber em '+w.dates.map(shortDate).join(', '):w.dates.length+' dias de entrada'}</div></div><strong>${C.money(w.amount)}</strong></div>`).join(''):'<p class="small">Nenhum dia de recebimento restante neste mês. Ajuste o calendário se houver outra entrada prevista.</p>'}${f.offSchedule?`<div class="line row"><span>Entrada fora do calendário</span><strong>${C.money(f.offSchedule)}</strong></div>`:''}<div class="tally"><span>Total que falta</span><strong>${C.money(f.needed)}</strong></div></div></section>
 <details class="card goal-details"><summary>Como chegamos à meta</summary><div class="line row"><span>Contas deste mês ainda não pagas</span><strong>${C.money(f.fixed)}</strong></div><div class="line row"><span>Dia a dia previsto até ${shortDate(f.end)}</span><strong>${C.money(f.livingTotal)}</strong></div><div class="line row"><span>Sobra desejada</span><strong>${C.money(p.buffer)}</strong></div><div class="line row"><span>Menos saldo disponível para o plano</span><strong>${C.money(f.available)}</strong></div><p class="small muted">${p.protectReserve?'A reserva atual de '+C.money(f.protectedAmount)+' fica fora do dinheiro disponível.':'Você permitiu usar a reserva no cálculo.'} A sobra desejada é adicional à reserva protegida.</p><p class="small muted">Gastos do dia a dia: ${C.money(state.weekly.daily)} por semana, em ${weekdaysText(p.spendDays)}. O gasto comum já registrado hoje abate o orçamento de hoje. Os outros dias são estimativas.</p><p class="small muted">Separar para contas é uma transferência, por isso não somamos esse valor novamente. A meta semanal de guardar não é uma conta: use a sobra desejada para incluir dinheiro novo que quer guardar.</p><p class="small muted">A previsão inclui as contas configuradas para este mês. Pendências de meses anteriores e despesas extras precisam entrar no seu plano. O sistema não conhece despesas não informadas.</p></details>
 <section class="card"><h2>Se não entrar mais dinheiro</h2><div class="goal-balance ${f.withoutIncome<0?'danger-text':'good'}" id="end-projection">${C.money(f.withoutIncome)}</div><p class="small muted">Saldo estimado após os gastos previstos${p.protectReserve?', preservando a reserva':''}. Não é uma previsão de renda garantida.</p></section>
 <div class="actions">${btn('income','+ Registrar entrada','primary')}${btn('goal-settings','Rever meu plano')}</div>`;
}
function daysFields(key,selected){return `<div class="weekday-options">${[1,2,3,4,5,6,0].map(d=>`<label><input type="checkbox" name="${key}" value="${d}" ${selected.includes(d)?'checked':''}><span>${weekdayShort[d]}</span></label>`).join('')}</div>`;}
function goalSettings(){
 const p=P.settings(state);
 openModal('Meu plano para fechar o mês',`<form id="goals-form"><p class="small muted">Informe valores reais ou uma estimativa que inclua todos os seus gastos. As metas se atualizam com os lançamentos.</p><fieldset><legend>Dias em que trabalho</legend>${daysFields('workdays',p.workdays)}</fieldset>
 <label for="goal-mode">Quando o dinheiro entra?</label><select id="goal-mode"><option value="weekly" ${p.paymentMode==='weekly'?'selected':''}>Uma vez por semana</option><option value="daily" ${p.paymentMode==='daily'?'selected':''}>Nos dias em que trabalho</option></select><div id="payday-wrap" ${p.paymentMode==='daily'?'hidden':''}><label for="goal-payday">Dia do recebimento</label><select id="goal-payday">${[1,2,3,4,5,6,0].map(d=>`<option value="${d}" ${p.payday===d?'selected':''}>${weekdayNames[d]}</option>`).join('')}</select></div>
 ${moneyField('goal-living','Gastos do dia a dia por semana (R$)',inputMoney(state.weekly.daily))}<p class="small muted">Alimentação, transporte e outros gastos comuns, sem repetir as contas fixas abaixo.</p><fieldset><legend>Em quais dias tenho esses gastos?</legend>${daysFields('spendDays',p.spendDays)}</fieldset>
 <h3 class="section">Contas mensais</h3>${state.bills.map(b=>`<div class="goal-bill"><div>${moneyField('goal-bill-'+b.id,esc(b.name),inputMoney(b.amount))}</div><div><label for="goal-due-${b.id}">Dia</label><input id="goal-due-${b.id}" type="number" min="1" max="28" value="${b.end}" required></div></div>`).join('')}<p class="small muted">Deixe zero nas contas que não usa. Vencimentos de 1 a 28. Valores pagos no mês já são descontados.</p>
 ${moneyField('goal-buffer','Quanto quero sobrar no fim do mês (R$)',inputMoney(p.buffer))}<p class="small muted">É o dinheiro que deseja manter além da reserva protegida. Zero calcula o mínimo para cobrir os gastos.</p><label class="check"><input id="goal-protect" type="checkbox" ${p.protectReserve?'checked':''}>Preservar minha reserva atual</label>
 <div id="form-error" class="form-error" role="alert"></div><div class="form-footer"><button class="btn primary full" type="submit">Salvar e calcular metas</button></div></form>`);
}
document.addEventListener('change',e=>{if(e.target.id==='goal-mode')$('payday-wrap').hidden=e.target.value==='daily';});
