const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../core.js'),Store=require('../web-store.js');
function base(){const s=C.initial();s.setup=true;s.accounts[0].opening=100000;s.weekly={daily:20000,fixed:30000,saving:15000,goal:200000};return s;}
function tx(kind,cents,more={}){return {id:Math.random().toString(36).slice(2),date:C.today(),kind,cents,account:'c6',...more};}
function storage(){const data=new Map();return {getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,v)};}
test('public defaults have no personal balances, transactions or planned amounts',()=>{const s=C.initial();assert.ok(s.accounts.every(a=>a.opening===0));assert.deepEqual(s.transactions,[]);assert.ok(s.bills.every(b=>b.amount===0));assert.ok(Object.values(s.weekly).every(n=>n===0));});
test('Brazilian values use integer cents and reject ambiguous input',()=>{assert.equal(C.parseMoney('1.234,56'),123456);assert.equal(C.parseMoney('0,01'),1);assert.throws(()=>C.parseMoney('10.50'));assert.throws(()=>C.parseMoney('-10'));assert.throws(()=>C.parseMoney('10,001'));});
test('transfer conserves money and does not become income or expense',()=>{const s=C.add(base(),tx('transfer',30000,{to:'nu'}));assert.deepEqual(C.balances(s),{c6:70000,nu:30000,mp:0});assert.equal(C.totals(s,C.today().slice(0,7)).income,0);assert.equal(C.totals(s,C.today().slice(0,7)).expense,0);});
test('bill payment reduces balance and applies only to its month',()=>{let s=C.add(base(),tx('transfer',30000,{to:'nu'}));s=C.add(s,tx('expense',20000,{account:'nu',bill:'rent',billMonth:'2026-10'}));assert.equal(C.balances(s).nu,10000);assert.equal(C.paid(s,'rent','2026-10'),20000);assert.equal(C.paid(s,'rent','2026-11'),0);});
test('plan respects configured values on every date without a personal October override',()=>{const s=base();for(const date of ['2026-10-10','2026-10-17','2027-01-02'])assert.deepEqual(C.split(s,80000,date),{fixed:30000,daily:20000,save:15000,margin:15000,shortfall:0,bootstrap:false});assert.equal(C.split(s,40000,'2026-10-10').shortfall,10000);assert.equal(C.split(s,40000,'2026-10-10').save,0);});
test('overspending, duplicate source and invalid transfers are rejected',()=>{assert.throws(()=>C.add(base(),tx('expense',100001)));assert.throws(()=>C.add(base(),tx('transfer',100,{to:'c6'})));const s=C.add(base(),tx('expense',1000,{sourceId:'bank_1'}));assert.throws(()=>C.add(s,tx('expense',1000,{sourceId:'bank_1'})));});
test('backup validates and rejects altered bank roles',()=>{const s=base();assert.deepEqual(C.validate(JSON.parse(JSON.stringify(s))),s);s.accounts[1].role='daily';assert.throws(()=>C.validate(s));});
test('save survives a new browser store instance',()=>{const backend=storage(),one=new Store(backend,C.validate);assert.equal(one.load(),null);one.save(base());const two=new Store(backend,C.validate);assert.deepEqual(two.load(),base());});
test('storage write failure leaves the previous saved data intact',()=>{const backend=storage(),store=new Store(backend,C.validate);store.load();store.save(base());const previous=backend.getItem(Store.KEY);backend.setItem=()=>{throw Error('QuotaExceeded');};assert.throws(()=>store.save(C.add(base(),tx('income',1000))),/Não foi possível salvar/);assert.equal(backend.getItem(Store.KEY),previous);});
test('corrupted storage is preserved instead of reset',()=>{const backend=storage();backend.setItem(Store.KEY,'broken json');const store=new Store(backend,C.validate);assert.throws(()=>store.load());assert.throws(()=>store.save(base()));assert.equal(backend.getItem(Store.KEY),'broken json');});
test('stale browser tab cannot overwrite newer transactions',()=>{const backend=storage(),one=new Store(backend,C.validate),two=new Store(backend,C.validate);one.load();one.save(base());two.load();one.save(C.add(base(),tx('income',1000)));assert.throws(()=>two.save(base()),/outra aba/);assert.equal(C.balances(two.load()).c6,101000);});
